<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Checkup Motor Parts Admin')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php 
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('http://cdn.sencha.io/ext-4.2.0-gpl/resources/css/ext-all.css');
        ?>

        

    </head>
    <body>

        <div id="container"></div>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('http://cdn.sencha.io/ext-4.2.0-gpl/ext-all.js')
            ->prependFile($this->basePath() . '/js/lib/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/lib/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <script type="text/javascript">
            Ext.Loader.setConfig({enabled: true });

            Ext.Loader.setConfig({
                enabled: true,
                //disableCaching: false,
                paths: {
                    "Checkup": "js"
                }
            }); 
        </script>

        <?php echo $this->content; ?>
    </body>
</html>
