<style type="text/css">
    #tabpanel-main .x-panel-header,
    #tabpanel-main .x-tab-bar,
    #tabpanel-main #tabpanel-main-body {
        width   : 100% !important;
    }

    .x-livesearch-match {
        font-weight: bold;
        background-color: yellow;
    }

    .x-tool-mytool {
        /*background-image: url(<?php echo $this->basePath() . '/img/favicon.ico'; ?>) !important;*/
    }  
</style>
<script type="text/javascript">
   Ext.create('Checkup.Panel');
</script>