<style type="text/css">
    .x-panel-header,
    .x-tab-bar,
    #tabpanel-main-body {
        width   : 100% !important;
    }

    .x-livesearch-match {
        font-weight: bold;
        background-color: yellow;
    }

    .x-tool-mytool {
        /*background-image: url(<?php echo $this->basePath() . '/img/favicon.ico'; ?>) !important;*/
    } 

    #txt-username-inputEl,
    #txt-password-inputEl
    {
        width : 97% !important;
    }

    #login-window {
        height : 153px !important;
        width : 300px !important;
    }

    #ext-gen1038
    {
        height : 149px !important;
        width : 300px !important;
    }

    #login-window_header
    {
        width : 300px !important;
    }
</style>
<script type="text/javascript">
    Ext.create('Checkup.Login.Window.Login').show();
</script>